Invoke-PS2EXE `
  -InputFile "MenuPrincipal.ps1" `
  -OutputFile "secretaria_virtual.exe" `
  -Title "Secretaria Virtual" `
  -Description "IA - Software para uma secretaria virtual com Nuvem." `
  -Company "Spacedwog" `
  -Product "Sistema de Secretaria Virtual" `
  -Version "1.0.0.0" `
  -Copyright "Copyright (c) 2025 Felipe Rodrigues dos Santos" `
  -noConsole `
  -IconFile "icone.ico" `
  -Verbose